using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SqlCore.Engine.TransactionLog
{
    public static class LogOperation
    {
        public static string GetLogOperationDesc(byte logOperation) => 
            logOperation switch
            {
                0x00 => "LOP_NULL",
                0x01 => "LOP_FORMAT_PAGE",
                0x02 => "LOP_INSERT_ROWS",
                0x03 => "LOP_DELETE_ROWS",
                0x04 => "LOP_MODIFY_ROW",
                0x05 => "LOP_MODIFY_HEADER",
                0x06 => "LOP_MODIFY_COLUMNS",
                0x07 => "LOP_SET_BITS",
                0x0a => "LOP_SET_FREE_SPACE",
                0x0b => "LOP_DELETE_SPLIT",
                0x0c => "LOP_UNDO_DELETE_SPLIT",
                0x0d => "LOP_EXPUNGE_ROWS",
                0x10 => "LOP_FILE_HDR_MODIFY",
                0x11 => "LOP_CLEAR_GAM_BITS",
                0x12 => "LOP_COUNT_DELTA",
                0x13 => "LOP_ROOT_CHANGE",
                0x14 => "LOP_COMPRESSION_INFO",
                0x15 => "LOP_ENCRYPT_PAGE",
                0x16 => "LOP_INSYSXACT",
                0x7b => "LOP_REVERT_ROW",
                0x7c => "LOP_RECONFIGURE",
                0x7d => "LOP_STRIP_VERSION_INFO",
                0x7e => "LOP_RESET_VERSION_INFO",
                0x80 => "LOP_BEGIN_XACT",
                0x81 => "LOP_COMMIT_XACT",
                0x82 => "LOP_ABORT_XACT",
                0x83 => "LOP_PREP_XACT",
                0x84 => "LOP_MARK_SAVEPOINT",
                0x85 => "LOP_FORGET_XACT",
                0x86 => "LOP_CREATE_FILE",
                0x87 => "LOP_DROP_FILE",
                0x88 => "Unknown",
                0x89 => "LOP_HOBT_DDL",
                0x8a => "LOP_IDENT_NEWVAL",
                0x8b => "LOP_IDENT_SENTVAL",
                0x8c => "LOP_HOBT_DELTA",
                0x8d => "LOP_LOCK_XACT",
                0x8e => "LOP_CREATE_STREAMFILE",
                0x8f => "LOP_MIGRATE_LOCKS",
                0x90 => "LOP_DROP_STREAMFILE",
                0x91 => "LOP_FS_DOWNLEVEL_OP",
                0x92 => "LOP_MODIFY_STREAMFILE_HDR",
                0x93 => "LOP_FS_CONTAINER_SIZE_DELTA",
                0x94 => "LOP_BP_DBVER",
                0x95 => "LOP_COPY_VERSION_INFO",
                0x96 => "LOP_BEGIN_CKPT",
                0x98 => "LOP_XACT_CKPT",
                0x99 => "LOP_END_CKPT",
                0x9a => "LOP_BUF_WRITE",
                0xa0 => "LOP_BEGIN_RECOVERY",
                0xa1 => "LOP_END_RECOVERY",
                0xa2 => "LOP_TENANT_LOG",
                0xad => "LOP_CREATE_INDEX",
                0xae => "LOP_DROP_INDEX",
                0xb0 => "LOP_CREATE_ALLOCCHAIN",
                0xb4 => "LOP_CREATE_FTCAT",
                0xb5 => "LOP_DROP_FTCAT",
                0xc8 => "LOP_REPL_COMMAND",
                0xc9 => "LOP_BEGIN_UPDATE",
                0xca => "LOP_END_UPDATE",
                0xcb => "LOP_TEXT_POINTER",
                0xcc => "LOP_TEXT_INFO_BEGIN",
                0xcd => "LOP_TEXT_INFO_END",
                0xce => "LOP_REPL_NOOP",
                0xcf => "LOP_TEXT_VALUE",
                0xd3 => "LOP_SHRINK_NOOP",
                0xd4 => "LOP_FILESTREAM_INFO_BEGIN",
                0xd5 => "LOP_FILESTREAM_INFO_END",
                0xd6 => "LOP_BULK_EXT_ALLOCATION",
                0xd7 => "LOP_SECURITY_OP",
                0xd8 => "LOP_PAGE_REENCRYPT",
                0xd9 => "LOP_CREATE_PHYSICAL_FILE",
                0xdc => "LOP_RANGE_INSERT",
                0xdd => "LOP_INVALIDATE_CACHE",
                0xdf => "LOP_CSI_ROWGROUP",
                0xe0 => "LOP_CSI_DELETE_BUFFER",
                0xe1 => "LOP_CSI_DBMP_INVALIDATION",
                0xe6 => "LOP_HK",
                0xe7 => "LOP_HK_CHECKPOINT",
                0xe8 => "LOP_HK_CHAINED",
                0xe9 => "LOP_HK_DEPLOYED",
                0xea => "LOP_HK_UNDEPLOYED",
                0xf0 => "LOP_SEREPL_MSG",
                0xf1 => "LOP_AUDIT",
                0xf2 => "LOP_SLOG_CKPT",
                0xf3 => "LOP_PREPARE_REMOTE_FILE",
                0xf4 => "LOP_CTR_NEST_ABORT",
                0xf5 => "LOP_EE",
                0xf6 => "LOP_CTR_NEST_BEGIN"
            };
    }
}
